queue_rules:
  - name: Merge Queue
    merge_method: merge
    update_method: rebase
    autoqueue: true
    queue_conditions:
      - and:
          - author = dependabot[bot]
merge_protections:
  - name: Require review from code owners
    if:
      - base = main
    success_conditions:
      - approved-reviews-by = michael-valdron
